# Generated by Django 4.2.4 on 2023-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('telegram', models.CharField(max_length=33)),
                ('number', models.CharField(max_length=12)),
                ('text_about', models.TextField()),
                ('is_student', models.BooleanField(default=True)),
                ('course', models.IntegerField()),
                ('is_ended', models.BooleanField(default=False)),
                ('step', models.TextField()),
                ('faculty', models.TextField()),
                ('program', models.TextField()),
                ('job', models.TextField()),
            ],
        ),
    ]
